data = [
  { "kana": "月ノ美兎", "eigo": "Tsukino Mito" },
  { "kana": "勇気ちひろ", "eigo": "Yuki Chihiro" },
  { "kana": "える", "eigo": "Elu" },
  { "kana": "樋口楓", "eigo": "Higuchi Kaede" },
  { "kana": "静凛", "eigo": "Shizuka Rin" },
  { "kana": "渋谷ハジメ", "eigo": "Shibuya Hajime" },
  { "kana": "鈴谷アキ", "eigo": "Suzuya Aki" },
  { "kana": "モイラ", "eigo": "Moira" },
  { "kana": "鈴鹿詩子", "eigo": "Suzuka Utako" },
  { "kana": "宇志海いちご", "eigo": "Ushimi Ichigo" },
  { "kana": "家長むぎ", "eigo": "Ienaga Mugi" },
  { "kana": "夕陽リリ", "eigo": "Yuhi Riri" },
  { "kana": "物述有栖", "eigo": "Mononobe Alice" },
  { "kana": "文野環", "eigo": "Fumino Tamaki" },
  { "kana": "伏見ガク", "eigo": "Fushimi Gaku" },
  { "kana": "ギルザレンIII世", "eigo": "Gilzaren III" },
  { "kana": "剣持刀也", "eigo": "Kenmochi Toya" },
  { "kana": "森中花咲", "eigo": "Morinaka Kazaki" },
  { "kana": "叶", "eigo": "Kanae" },
  { "kana": "赤羽葉子", "eigo": "Akabane Youko" },
  { "kana": "笹木咲", "eigo": "Sasaki Saku" },
  { "kana": "闇夜乃モルル", "eigo": "Yamiyono Moruru" },
  { "kana": "本間ひまわり", "eigo": "Honma Himawari" },
  { "kana": "魔界ノりりむ", "eigo": "Makaino Ririmu" },
  { "kana": "葛葉", "eigo": "Kuzuha" },
  { "kana": "雪汝", "eigo": "Setsuna" },
  { "kana": "椎名唯華", "eigo": "Shiina Yuika" },
  { "kana": "ドーラ", "eigo": "Dola" },
  { "kana": "海夜叉神", "eigo": "Umiyashanokami" },
  { "kana": "名伽尾アズマ", "eigo": "Nakao Azuma" },
  { "kana": "出雲霞", "eigo": "Izumo Kasumi" },
  { "kana": "轟京子", "eigo": "Todoroki Kyoko" },
  { "kana": "シスター・クレア", "eigo": "Sister Claire" },
  { "kana": "花畑チャイカ", "eigo": "Hanabatake Chaika" },
  { "kana": "社築", "eigo": "Yashiro Kizuku" },
  { "kana": "安土桃", "eigo": "Azuchi Momo" },
  { "kana": "鈴木勝", "eigo": "Suzuki Masaru" },
  { "kana": "緑仙", "eigo": "Ryushen" },
  { "kana": "卯月コウ", "eigo": "Uzuki Kou" },
  { "kana": "八朔ゆず", "eigo": "Hassaku Yuzu" },
  { "kana": "神田笑一", "eigo": "Kanda Shoichi" },
  { "kana": "鳴門こがね", "eigo": "Naruto Kogane" },
  { "kana": "飛鳥ひな", "eigo": "Asuka Hina" },
  { "kana": "春崎エアル", "eigo": "Harusaki Air" },
  { "kana": "雨森小夜", "eigo": "Amemori Sayo" },
  { "kana": "鷹宮リオン", "eigo": "Takamiya Rion" },
  { "kana": "舞元啓介", "eigo": "Maimoto Keisuke" },
  { "kana": "竜胆尊", "eigo": "Rindou Mikoto" },
  { "kana": "でびでび・でびる", "eigo": "Debidebi Debiru" },
  { "kana": "桜凛月", "eigo": "Sakura Ritsuki" },
  { "kana": "町田ちま", "eigo": "Machita Chima" },
  { "kana": "月見しずく", "eigo": "Tsukimi Shizuku" },
  { "kana": "ジョー・力一", "eigo": "Joe Rikiichi" },
  { "kana": "遠北千南", "eigo": "Achikita Chinami" },
  { "kana": "成瀬鳴", "eigo": "Naruse Naru" },
  { "kana": "ベルモンド・バンデラス", "eigo": "Belmond Banderas" },
  { "kana": "矢車りね", "eigo": "Yaguruma Rine" },
  { "kana": "夢追翔", "eigo": "Yumeoi Kakeru" },
  { "kana": "黒井しば", "eigo": "Kuroi Shiba" },
  { "kana": "童田明治", "eigo": "Warabeda Meiji" },
  { "kana": "久遠千歳", "eigo": "Kudo Chitose" },
  { "kana": "郡道美玲", "eigo": "Gundo Mirei" },
  { "kana": "夢月ロア", "eigo": "Yuzuki Roa" },
  { "kana": "小野町春香", "eigo": "Onomachi Haruka" },
  { "kana": "語部紡", "eigo": "Kataribe Tsumugu" },
  { "kana": "瀬戸美夜子", "eigo": "Seto Miyako" },
  { "kana": "御伽原江良", "eigo": "Otogibara Era" },
  { "kana": "戌亥とこ", "eigo": "Inui Toko" },
  { "kana": "アンジュ・カトリーナ", "eigo": "Ange Katrina" },
  { "kana": "リゼ・ヘルエスタ", "eigo": "Lize Helesta" },
  { "kana": "三枝明那", "eigo": "Saegusa Akina" },
  { "kana": "愛園愛美", "eigo": "Aizono Manami" },
  { "kana": "鈴原るる", "eigo": "Suzuhara Lulu" },
  { "kana": "雪城眞尋", "eigo": "Yukishiro Mahiro" },
  { "kana": "エクス・アルビオ", "eigo": "Ex Albio" },
  { "kana": "レヴィ・エリファ", "eigo": "Levi Elipha" },
  { "kana": "葉山舞鈴", "eigo": "Hayama Marin" },
  { "kana": "ニュイ・ソシエール", "eigo": "Nui Sociere" },
  { "kana": "葉加瀬冬雪", "eigo": "Hakase Fuyuki" },
  { "kana": "加賀美ハヤト", "eigo": "Kagami Hayato" },
  { "kana": "夜見れな", "eigo": "Yorumi Rena" },
  { "kana": "黛灰", "eigo": "Mayuzumi Kai" },
  { "kana": "アルス・アルマル", "eigo": "Ars Almal" },
  { "kana": "相羽ういは", "eigo": "Aiba Uiha" },
  { "kana": "天宮こころ", "eigo": "Amamiya Kokoro" },
  { "kana": "エリー・コニファー", "eigo": "Eli Conifer" },
  { "kana": "ラトナ・プティ", "eigo": "Ratna Petit" },
  { "kana": "早瀬走", "eigo": "Hayase Sou" },
  { "kana": "健屋花那", "eigo": "Sukoya Kana" },
  { "kana": "シェリン・バーガンディ", "eigo": "Shellin Burgundy" },
  { "kana": "フミ", "eigo": "Fumi" },
  { "kana": "星川サラ", "eigo": "Hoshikawa Sara" },
  { "kana": "山神カルタ", "eigo": "Yamagami Karuta" },
  { "kana": "えま★おうがすと", "eigo": "Emma August" },
  { "kana": "ルイス・キャミー", "eigo": "Luis Cammy" },
  { "kana": "魔使マオ", "eigo": "Matsukai Mao" },
  { "kana": "不破湊", "eigo": "Fuwa Minato" },
  { "kana": "白雪巴", "eigo": "Shirayuki Tomoe" },
  { "kana": "グウェル・オス・ガール", "eigo": "Gwelu Os Gar" },
  { "kana": "ましろ爻", "eigo": "Mashiro Meme" },
  { "kana": "奈羅花", "eigo": "Naraka" },
  { "kana": "来栖夏芽", "eigo": "Kurusu Natsume" },
  { "kana": "フレン・E・ルスタリオ", "eigo": "Furen E Lustario" },
  { "kana": "メリッサ・キンレンカ", "eigo": "Melissa Kinrenka" },
  { "kana": "イブラヒム", "eigo": "Ibrahim" },
  { "kana": "長尾景", "eigo": "Nagao Kei" },
  { "kana": "弦月藤士郎", "eigo": "Genzuki Tojiro" },
  { "kana": "甲斐田晴", "eigo": "Kaida Haru" },
  { "kana": "空星きらめ", "eigo": "Sorahoshi Kirame" },
  { "kana": "朝日南アカネ", "eigo": "Asahina Akane" },
  { "kana": "周央サンゴ", "eigo": "Suo Sango" },
  { "kana": "東堂コハク", "eigo": "Todo Kohaku" },
  { "kana": "北小路ヒスイ", "eigo": "Kitakoji Hisui" },
  { "kana": "西園チグサ", "eigo": "Nishizono Chigusa" },
  { "kana": "アクシア・クローネ", "eigo": "Axia Krone" },
  { "kana": "ローレン・イロアス", "eigo": "Lauren Iroas" },
  { "kana": "レオス・ヴィンセント", "eigo": "Leos Vincent" },
  { "kana": "オリバー・エバンス", "eigo": "Oliver Evans" },
  { "kana": "レイン・パターソン", "eigo": "Lain Paterson" },
  { "kana": "天ヶ瀬むゆ", "eigo": "Amagase Muyu" },
  { "kana": "先斗寧", "eigo": "Ponto Nei" },
  { "kana": "海妹四葉", "eigo": "Umise Yotsuha" },
  { "kana": "壱百満天原サロメ", "eigo": "Hyakumantenbara Salome" },
  { "kana": "風楽奏斗", "eigo": "Fura Kanato" },
  { "kana": "渡会雲雀", "eigo": "Watarai Hibari" },
  { "kana": "四季凪アキラ", "eigo": "Shikinagi Akira" },
  { "kana": "セラフ・ダズルガーデン", "eigo": "Seraph Dazzlegarden" },
  { "kana": "小清水透", "eigo": "Koshimizu Toru" },
  { "kana": "獅子堂あかり", "eigo": "Shishido Akari" },
  { "kana": "鏑木ろこ", "eigo": "Kaburaki Roco" },
  { "kana": "五十嵐梨花", "eigo": "Igarashi Rika" },
  { "kana": "石神のぞみ", "eigo": "Ishigami Nozomi" },
  { "kana": "ソフィア・ヴァレンタイン", "eigo": "Sophia Valentine" },
  { "kana": "倉持めると", "eigo": "Kuramochi Meruto" },
  { "kana": "佐伯イッテツ", "eigo": "Saiki Ittetsu" },
  { "kana": "赤城ウェン", "eigo": "Akagi Wen" },
  { "kana": "宇佐美リト", "eigo": "Usami Rito" },
  { "kana": "緋八マナ", "eigo": "Hibachi Mana" },
  { "kana": "星導ショウ", "eigo": "Hoshirube Sho" },
  { "kana": "叢雲カゲツ", "eigo": "Murakumo Kagetsu" },
  { "kana": "小柳ロウ", "eigo": "Koyanagi Rou" },
  { "kana": "伊波ライ", "eigo": "Inami Rai" },
  { "kana": "立伝都々", "eigo": "Tachitsute Toto" },
  { "kana": "栞葉るり", "eigo": "Shioriha Ruri" },
  { "kana": "ミラン・ケストレル", "eigo": "Milan Kestrel" },
  { "kana": "北見遊征", "eigo": "Kitami Yusei" },
  { "kana": "魁星", "eigo": "Kaisei" },
  { "kana": "榊ネス", "eigo": "Sakaki Ness" },
]